### ISSUE TITLE
Ask for dataset

### ISSUE THREAD

**Issue by jamesnguyen123** [antoinedelplace/Cyberattack-Detection#1]
Hi Antoine Delplace,

I am Dinh, a PhD from Deakin univerisity. I am interested in your project. Can you share the dataset you used in the project which can help me run your codes?
Thanks and hope to hear your feedback soon!

**Comment by antoinedelplace** [comment]
Hi James,
You can find all the references, including a link to the CTU dataset, at the end of the paper.
Here to help you : **[CTU11]** CTU University. _The CTU-13 Dataset. A Labeled Dataset with Botnet, Normal and Background traffic._ 2011. url: [https://www.stratosphereips.org/datasets-ctu13](https://www.stratosphereips.org/datasets-ctu13) (visited on 03/29/2019).
Regards

**Comment by jamesnguyen123** [comment]
Thanks very much for your quick reply. I will refer it. Once I used your source, I will cite your work in my paper. I will keep in touch with you!
Thanks
